scala_library(
    name = "domain",
    srcs = glob(["**/*.scala"]),
    visibility = ["//visibility:public"],
    deps = [
        "//3rdparty/jvm/at/favre/lib:bcrypt",
        "//3rdparty/jvm/com/datastax/oss:java_driver_mapper_runtime",
    ],
)
