scala_library(
    name = "app",
    srcs = glob(["*.scala"]),
    visibility = ["//visibility:public"],
    deps = [
        "//3rdparty/jvm/com/datastax/oss:java_driver_core",
        "//src/scala/datastax/domain",
    ],
)
